# Generated by Django 4.2.30 on 2026-04-25 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default='default_user', max_length=255, unique=True)),
                ('language', models.CharField(default='English', max_length=50)),
                ('struggle_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('deep_dive_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LearningHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=255)),
                ('learned_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.userprofile')),
            ],
        ),
    ]
